"""Causal feature construction and verification."""

from .price_ohlc_v1 import (
    MAX_LAG_BARS,
    PRICE_OHLC_V1_FEATURE_NAMES,
    build_and_persist_features,
    build_feature_report,
    build_model_dataset,
    build_price_ohlc_v1_features,
    get_feature_names,
)
from .price_5m_v1 import (
    FINE_MAX_LAG_BARS,
    FINE_PATH_WINDOW_BARS,
    PRICE_5M_V1_FEATURE_NAMES,
    build_price_5m_v1_features,
    get_fine_feature_names,
)
from .multires import (
    build_and_persist_multires_features,
    build_b1_feature_report,
    build_multires_model_dataset,
    build_price_multires_features,
    project_feature_view_dataset,
)
from .views import (
    COARSE_30M_FEATURE_NAMES,
    B1_COARSE_FEATURE_NAMES,
    B1_FINE_FEATURE_NAMES,
    FEATURE_VIEWS,
    MULTIRES_FEATURE_NAMES,
    PRICE_MULTIRES_V1_FEATURE_NAMES,
    FeatureView,
    resolve_feature_view,
)
from .verification import (
    run_all_multires_checks,
    run_all_feature_checks,
    run_common_sample_equality_check,
    run_feature_alignment_check,
    run_feature_finite_check,
    run_feature_schema_check,
    run_future_mutation_check,
    run_gap_continuity_check,
    run_fine_alignment_contract_check,
    run_fine_future_mutation_check,
    run_fine_gap_continuity_check,
    run_multires_feature_finite_check,
    run_multires_feature_schema_check,
    run_multires_future_mutation_check,
    run_test_sealing_check,
)

__all__ = [
    "MAX_LAG_BARS",
    "FINE_MAX_LAG_BARS",
    "FINE_PATH_WINDOW_BARS",
    "COARSE_30M_FEATURE_NAMES",
    "B1_COARSE_FEATURE_NAMES",
    "B1_FINE_FEATURE_NAMES",
    "FEATURE_VIEWS",
    "FeatureView",
    "MULTIRES_FEATURE_NAMES",
    "PRICE_MULTIRES_V1_FEATURE_NAMES",
    "PRICE_OHLC_V1_FEATURE_NAMES",
    "PRICE_5M_V1_FEATURE_NAMES",
    "build_and_persist_multires_features",
    "build_b1_feature_report",
    "build_and_persist_features",
    "build_multires_model_dataset",
    "build_feature_report",
    "build_model_dataset",
    "build_price_5m_v1_features",
    "get_fine_feature_names",
    "build_price_multires_features",
    "build_price_ohlc_v1_features",
    "get_feature_names",
    "project_feature_view_dataset",
    "resolve_feature_view",
    "run_all_feature_checks",
    "run_all_multires_checks",
    "run_common_sample_equality_check",
    "run_feature_alignment_check",
    "run_feature_finite_check",
    "run_feature_schema_check",
    "run_future_mutation_check",
    "run_gap_continuity_check",
    "run_fine_alignment_contract_check",
    "run_fine_future_mutation_check",
    "run_fine_gap_continuity_check",
    "run_multires_feature_finite_check",
    "run_multires_feature_schema_check",
    "run_multires_future_mutation_check",
    "run_test_sealing_check",
]
